# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTokenBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=200)),
                ('active_flag', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=120)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('active_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('active_flag', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('active_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=200)),
                ('maket_limit', models.IntegerField()),
                ('active_flag', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('time_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_server.TimeLimit')),
            ],
        ),
        migrations.AddField(
            model_name='tokenkey',
            name='token_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_server.TokenType'),
        ),
        migrations.AddField(
            model_name='customertokenbinding',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_server.Market'),
        ),
        migrations.AddField(
            model_name='customertokenbinding',
            name='token_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_server.TokenKey'),
        ),
    ]
