# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertokenbinding',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='tokentype',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='tokenkey',
            name='customer_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tokenkey',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TimeLimit',
        ),
    ]
