# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-24 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_server', '0002_auto_20171224_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokentype',
            old_name='maket_limit',
            new_name='market_limit',
        ),
    ]
